###########################################|###########################################
#                                                                                     #
#                                   CONFIGURATOR PANEL                                #
#                                                                                     #
#                               Configurator panel setup                              #
#                                                                                     #
###########################################|###########################################

configurator:
  title: Configurator
  icon: mdi:wrench
  url: http://192.168.1.40:3218