###########################################|###########################################
#                                                                                     #
#                                     HARMONY HUB                                     #
#                                                                                     #
#                            Harmony Hub manual configuration                         #
#                                                                                     #
###########################################|###########################################

- platform: harmony
  name: "Harmony Hub"
  host: 192.168.1.51