###########################################|###########################################
#                                                                                     #
#                                   PI SYSTEM MONITOR                                 #
#                                                                                     #
#                   Sensor to show the current Pi's system usage                      #
#                                                                                     #
###########################################|###########################################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: since_last_boot
    - type: last_boot
    