###########################################|###########################################
#                                                                                     #
#                                NURSERY HEATER SWITCH                                #
#                                                                                     #
#                  Binary sensor to show if the nursery heater is ON                  #
#                                                                                     #
###########################################|###########################################

- platform: template
  sensors:
    nursery_heater:
      friendly_name: "Nursery Heater"
      device_class: power
      value_template: "{{ is_state('switch.nursery_heater_switch', 'on') }}"