###########################################|###########################################
#                                                                                     #
#                                 UPTIME ROBOT SENSORS                                #
#                                                                                     #
#              Create sesnors for the monitors set up on uptimerobot.com              #
#                                                                                     #
###########################################|###########################################

- platform: uptimerobot
  api_key: u451426-1195cf50436c192105132877