###########################################|###########################################
#                                                                                     #
#                                LOUNGE SOUNDBAR COVER                                #
#                                                                                     #
#             Cover to run VOLUME UP and DOWN scripts for lounge soundbar             #
#                                                                                     #
###########################################|###########################################

- platform: template
  covers:
    soundbar_volume:
      friendly_name: "Soundbar Volume"
      value_template: "{{ is_state('switch.xbox', 'on')}}"
      open_cover:
        service: script.turn_on
        data:
          entity_id: script.soundbar_volume_up
      close_cover:
        service: script.turn_on
        data:
          entity_id: script.soundbar_volume_down
      stop_cover:
        service: script.turn_on
        data:
          entity_id: script.soundbar_volume_mute