###########################################|###########################################
#                                                                                     #
#                                      LOUNGE TV                                      #
#                                                                                     #
#                   Manual configuration of lounge Samsung TV                         #
#                                                                                     #
###########################################|###########################################
# NOTE: Used in automations to check whether the lounge TV is ON/OFF #
######################################################################

- platform: samsungtv
  host: 192.168.1.24
  name: Lounge TV
  mac: FC:8F:90:E8:73:69