###########################################|###########################################
#                                                                                     #
#                                GOOGLE TEXT TO SPEECH                                #
#                                                                                     #
#                              Google tts configuration                               #
#                                                                                     #
###########################################|###########################################

- platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  base_url: http://192.168.1.40:8123